### ISSUE TITLE
在rk3128上提示usb bulk send error

### ISSUE THREAD

**Issue by qdk0901** [xboot/xrock#5]
在usb_bulk_send里打印具体错误后，发现是先发生pipe error，后发生timed out错误

```
PS D:\devel\rk\xrock\xrock> .\xrock.exe maskrom ..\RK3128_DDR_300M_V2.08.bin usbplug ..\rk3128_usbplug_v2.57.bin
PS D:\devel\rk\xrock\xrock> .\xrock.exe version
usb bulk send error: Pipe error
PS D:\devel\rk\xrock\xrock> .\xrock.exe version
usb bulk send error: Operation timed out
PS D:\devel\rk\xrock\xrock
```

**Comment by jianjunjiang** [comment]
安装xrock驱动了吗？不要用RK官方的，另外需要确认进入maskrom模式。

sudo xrock maskrom rk3128_ddr_300MHz_v2.12.bin rk3128_usbplug_v2.63.bin
sudo xrock version

**Comment by qdk0901** [comment]
xrock驱动装了，rk官方的驱动也卸载了，是在windows下跑
也执行了xrock maskrom命令
![image](https://user-images.githubusercontent.com/1351536/169017842-a30208cd-d68a-4bc1-aae8-4adb31fc4145.png)

测了ddr3的板子也是一样的现象
![image](https://user-images.githubusercontent.com/1351536/169018492-2ec86603-d28d-4f77-a1c3-2f0ec42a37ce.png)

在ubuntu下也是一样的现象
![image](https://user-images.githubusercontent.com/1351536/169021260-35114a31-e6db-4918-87cd-8d7aeebc0c7a.png)

**Comment by jianjunjiang** [comment]
换下bin文件， rk3128_ddr_300MHz_v2.12.bin rk3128_usbplug_v2.63.bin，也许你那bin文件不行，跟你板子对不上

**Comment by jianjunjiang** [comment]
要确认是进入了maskrom模式，非loader模式

**Comment by qdk0901** [comment]
换了这两个也是一样
 rk3128_ddr_300MHz_v2.12.bin rk3128_usbplug_v2.63.bin，
确认是maskrom模式

**Comment by jianjunjiang** [comment]
那就奇怪了，先进loader模式，用xrock其他指令测试下，version，capability， hexdump等，验证硬件连接是否正常，或者板子是否能正常运行
